name: conveyor-detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - opencv>=4.8.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - pip
  - pip:
    - ultralytics>=8.0.0
    - mlflow>=2.4.0
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - hydra-core>=1.3.0
    - python-dotenv>=1.0.0
    - rich>=13.0.0
    - onnx>=1.14.0
    - onnxruntime>=1.15.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - flake8>=6.0.0
    - fastapi>=0.100.0
    - uvicorn>=0.22.0
    - gradio>=3.35.0
    - imageio>=2.31.0
    - imageio-ffmpeg>=0.4.8
    - plotly>=5.14.0
