# Training Configuration for Conveyor Object Detection System

# Model Configuration
model:
  name: "yolov8m"  # Options: yolov8n, yolov8s, yolov8m, yolov8l, yolov8x, yolov7
  pretrained: true
  num_classes: 2
  class_names: ["bottle", "box"]

# Dataset Configuration
data:
  dataset_path: "data/dataset.yaml"
  train_split: 0.8
  val_split: 0.15
  test_split: 0.05
  augmentation:
    enabled: true
    mosaic: 1.0
    mixup: 0.1
    copy_paste: 0.3
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 10.0
    translate: 0.1
    scale: 0.9
    shear: 2.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5

# Training Parameters
training:
  epochs: 300
  batch_size: 16
  imgsz: 640
  patience: 50
  save_period: 10
  workers: 8
  device: "auto"  # auto, cpu, 0, 1, 2, etc.
  
  # Optimizer
  optimizer: "AdamW"  # SGD, Adam, AdamW
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

  # Loss weights
  box: 7.5
  cls: 0.5
  dfl: 1.5

# Validation Configuration
validation:
  val_period: 1
  save_json: true
  save_hybrid: false
  conf_thres: 0.001
  iou_thres: 0.6
  max_det: 300
  half: false
  dnn: false

# Logging and Experiment Tracking
logging:
  project_name: "conveyor-detection"
  experiment_name: "yolov8m-baseline"
  save_dir: "runs/train"
  log_metrics: true
  log_images: true
  log_model: true
  
  # MLflow settings
  mlflow:
    enabled: true
    tracking_uri: "mlruns"
    experiment_name: "conveyor-object-detection"
  
  # Weights & Biases settings
  wandb:
    enabled: false
    project: "conveyor-detection"
    entity: null

# Hardware and Performance
hardware:
  mixed_precision: true
  compile: false  # PyTorch 2.0 compile
  profile: false

# Reproducibility
seed: 42
deterministic: true
